
const TEST = 'TEST';
const CLOSE = 'CLOSE';
const INITIALIZE  = 'INITIALIZE';
const HYBRIDDATA  = 'HYBRIDDATA';
const MONODATA  = 'MONODATA';
const ROLE  = 'ROLE';
const FLYGRADE  = 'FLYGRADE';
const SUBSIDYPOLICY  = 'SUBSIDYPOLICY';
const SETCITY  = 'SETCITY';
const SETAIRTYPE  = 'SETAIRTYPE';
const OPENSCREEN  = 'OPENSCREEN';
const SETELECT  = 'SETELECT';
const ROUTERNETWORK  = 'ROUTERNETWORK';
const CHANGERENEW  = 'CHANGERENEW';
const TAGREAD  = 'TAGREAD';
const CHANGEORDER  = 'CHANGEORDER';

export {
    TEST,
    CLOSE,
    INITIALIZE,
    HYBRIDDATA,
    MONODATA,
    ROLE,
    FLYGRADE,
    SUBSIDYPOLICY,
    SETCITY,
    SETAIRTYPE,
    OPENSCREEN,
    SETELECT,
    ROUTERNETWORK,
    CHANGERENEW,
    TAGREAD,
    CHANGEORDER,
}
